from collections import namedtuple

PDFName = namedtuple("PDFName", ["value"])
PDFKeyword = namedtuple("PDFKeyword", ["value"])
PDFHexString = namedtuple("PDFHexString", ["value"])
PDFSingleton = namedtuple("PDFSingleton", ["value"])
PDFStreamReader = namedtuple("PDFStreamReader", ["value"])
PDFOperator = namedtuple("PDFOperator", ["value"])
PDFDictDelimiter = namedtuple("PDFDictDelimiter", ["value"])
PDFLiteralString = namedtuple("PDFLiteralString", ["value"])
PDFStream = namedtuple("PDFStream", ["dictionary", "stream"])
PDFReference = namedtuple("PDFReference", ["object_number", "generation_number"])
PDFIndirectObject = namedtuple("PDFIndirectObject", ["object_number", "generation_number", "value"])
XrefInUseEntry = namedtuple("XrefInUseEntry", ["offset", "object_number", "generation_number"])
XrefCompressedEntry = namedtuple("XrefCompressedEntry", ["object_number", "objstm_number", "index"])